name: Deploy Kind

on:
 
  push:
    branches: [ users/stephen ]

jobs:
        test:
          runs-on: ubuntu-latest
      
          steps:
            - name: checkout@scm
              uses: actions/checkout@v2
      
            - name: setup@kindconfig
              run: |
                export KUBECONFIG="$(kind get kubeconfig-path)"
                kubectl cluster-info
                #kind_in="${{ github.workspace }}/.github/config/kind.yml.in"
                #kind_out="${{ github.workspace }}/.github/config/kind.yml"
                #hostip=$(sh .github/scripts/get-host-ip.sh)
                #sed "s/127.0.0.1/$hostip/g" $kind_in > $kind_out
      
            - name: setup@kubernetes
              uses: engineerd/setup-kind@v0.5.0
              with:
                config: .github/config/kind.yml
      
            - name: setup@kubeconfig
              run: |
                hostip=$(sh .github/scripts/get-host-ip.sh)
                sed "s/127.0.0.1/$hostip/g" $HOME/.kube/config > ${{ github.workspace }}/kubeconfig.yml
# jobs:
#     kind:
#         runs-on: ubuntu-latest
#         env:
#             ACTIONS_ALLOW_UNSECURE_COMMANDS: true
#         steps:
#           - uses: actions/checkout@master
#           - uses: engineerd/setup-kind@v0.5.0
#           - name: Testing
#             run: |
#               export KUBECONFIG="$(kind get kubeconfig-path)"
#               kubectl cluster-info